name: Deploy Backend to Docker Hub and Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build backend Docker image
      run: |
        docker build -t emiruuzun/personel-faberk-backend:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push backend Docker image to Docker Hub
      run: |
        docker push emiruuzun/personel-faberk-backend:latest

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
            cd /root/personel-faberk  # Doğru klasöre geçiş
            # Docker Compose işlemleri
            if [ -f docker-compose.yml ]; then
              echo "docker-compose.yml bulundu, işlemler başlatılıyor..."
              docker-compose down
              docker rm -f $(docker ps -a -q --filter "name=nginx") || true
              docker rm -f $(docker ps -a -q --filter "name=frontend") || true
              docker rm -f $(docker ps -a -q --filter "name=backend") || true
              docker-compose up -d --build
            else
              echo "docker-compose.yml bulunamadı, işlem iptal edildi."
              exit 1
            fi

